
package hotel;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUMNO
 */
public class Reservacion extends javax.swing.JFrame {

    
    public Reservacion() {
        initComponents();
        // Desactivar la capacidad de agrandar la ventana
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        portadaRegistro = new javax.swing.JLabel();
        LogoRegistro = new javax.swing.JLabel();
        Reservacion = new javax.swing.JLabel();
        Sucursal = new javax.swing.JLabel();
        cmbxSucursal = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        CcbxEntrada = new de.wannawork.jcalendar.JCalendarComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        Salida = new javax.swing.JLabel();
        CcbxSalida = new de.wannawork.jcalendar.JCalendarComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        txtHabitacion = new javax.swing.JTextField();
        txtHuesped = new javax.swing.JTextField();
        Habitaciones = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Huespedes = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnHabitacion = new javax.swing.JButton();
        Visa = new javax.swing.JLabel();
        bccp = new javax.swing.JLabel();
        bccp2 = new javax.swing.JLabel();
        bccp3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 242, 235));

        portadaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portada12.png"))); // NOI18N

        LogoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        Reservacion.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Reservacion.setForeground(new java.awt.Color(134, 179, 0));
        Reservacion.setText("RESERVACIONES");

        Sucursal.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Sucursal.setForeground(new java.awt.Color(146, 195, 2));
        Sucursal.setText("Sucursal");

        cmbxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "-Palmetto La Perla", "-Palmetto San Borja", "-Palmetto San Miguel" }));
        cmbxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxSucursalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(146, 195, 2));
        jLabel13.setText("Entrada");

        CcbxEntrada.setBackground(new java.awt.Color(255, 255, 255));
        CcbxEntrada.setForeground(new java.awt.Color(255, 255, 255));

        Salida.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Salida.setForeground(new java.awt.Color(146, 195, 2));
        Salida.setText("Salida");

        CcbxSalida.setBackground(new java.awt.Color(255, 255, 255));
        CcbxSalida.setForeground(new java.awt.Color(255, 255, 255));

        txtHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHuespedActionPerformed(evt);
            }
        });

        Habitaciones.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Habitaciones.setForeground(new java.awt.Color(140, 186, 0));
        Habitaciones.setText("Habitaciones");

        Huespedes.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Huespedes.setForeground(new java.awt.Color(140, 186, 0));
        Huespedes.setText("Huéspedes ");

        btnHabitacion.setBackground(new java.awt.Color(126, 168, 0));
        btnHabitacion.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        btnHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnHabitacion.setText("Reservar Habitación ");
        btnHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionActionPerformed(evt);
            }
        });

        Visa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Visa.png"))); // NOI18N

        bccp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bbva.png"))); // NOI18N

        bccp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mastercard.png"))); // NOI18N

        bccp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diners_payment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Huespedes)
                                    .addComponent(Habitaciones)
                                    .addComponent(Salida)
                                    .addComponent(jLabel13)
                                    .addComponent(Sucursal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Visa)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bccp)
                                        .addGap(70, 70, 70)
                                        .addComponent(bccp3)
                                        .addGap(12, 12, 12))
                                    .addComponent(btnHabitacion))
                                .addGap(36, 36, 36)
                                .addComponent(bccp2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LogoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(CcbxEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CcbxSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHabitacion)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reservacion)
                        .addGap(136, 136, 136)))
                .addComponent(portadaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(portadaRegistro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LogoRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reservacion)
                .addGap(7, 7, 7)
                .addComponent(Sucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CcbxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CcbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Habitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Huespedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bccp3)
                                    .addComponent(bccp2)))
                            .addComponent(Visa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bccp))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHuespedActionPerformed

    private void btnHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionActionPerformed
        String sucursal = cmbxSucursal.getSelectedItem().toString();
        String habitacion = txtHabitacion.getText();
        String huesped = txtHuesped.getText();
        Date entradaDate = CcbxEntrada.getDate();
        Date salidaDate = CcbxSalida.getDate();

        if (sucursal.equals("Seleccione") || entradaDate == null || salidaDate == null || habitacion.isEmpty() || huesped.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
        } else if (entradaDate.after(salidaDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de entrada no puede ser posterior a la fecha de salida.");
        } else {
        switch (sucursal) {
            case "-Palmetto La Perla":
                PalmettoLaPerla palmettoLaPerla = new PalmettoLaPerla(sucursal, habitacion, huesped, entradaDate, salidaDate);
                palmettoLaPerla.setVisible(true);
                this.dispose();
                break;
            case "-Palmetto San Borja":
                PalmettoSanBorja palmettoSanBorja = new PalmettoSanBorja(sucursal, habitacion, huesped, entradaDate, salidaDate);
                palmettoSanBorja.setVisible(true);
                this.dispose();    
                break;
            case "-Palmetto San Miguel":
                PalmettoSanMiguel palmettoSanMiguel = new PalmettoSanMiguel(sucursal, habitacion, huesped, entradaDate, salidaDate);
                palmettoSanMiguel.setVisible(true);
                this.dispose();
                break;
            default:
                break;
        }
    
  }    }//GEN-LAST:event_btnHabitacionActionPerformed

    private void cmbxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.wannawork.jcalendar.JCalendarComboBox CcbxEntrada;
    private de.wannawork.jcalendar.JCalendarComboBox CcbxSalida;
    private javax.swing.JLabel Habitaciones;
    private javax.swing.JLabel Huespedes;
    private javax.swing.JLabel LogoRegistro;
    private javax.swing.JLabel Reservacion;
    private javax.swing.JLabel Salida;
    private javax.swing.JLabel Sucursal;
    private javax.swing.JLabel Visa;
    private javax.swing.JLabel bccp;
    private javax.swing.JLabel bccp2;
    private javax.swing.JLabel bccp3;
    private javax.swing.JButton btnHabitacion;
    private javax.swing.JComboBox<String> cmbxSucursal;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel portadaRegistro;
    private javax.swing.JTextField txtHabitacion;
    private javax.swing.JTextField txtHuesped;
    // End of variables declaration//GEN-END:variables
}
