/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_grafica;

/**
 *
 * @author USER
 */
public class interfac2 extends javax.swing.JFrame {

    /**
     * Creates new form interfac2
     */
    public interfac2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelNroBillete = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelOrigen = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelItenerario = new javax.swing.JLabel();
        labelNroCompañia = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("   BILLETE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n\t  |   \t         | \t           |          \t                  | \t \t    | \t              |  \t\t        | \t\n");
        jScrollPane1.setViewportView(jTextArea1);

        labelNroBillete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNroBillete.setForeground(new java.awt.Color(0, 0, 153));
        labelNroBillete.setText("NroBillete");

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 0, 153));
        labelFecha.setText("Fecha");

        labelHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHora.setForeground(new java.awt.Color(0, 0, 153));
        labelHora.setText("Hora");

        labelOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelOrigen.setForeground(new java.awt.Color(0, 0, 153));
        labelOrigen.setText("Origen");

        labelDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDestino.setForeground(new java.awt.Color(0, 0, 153));
        labelDestino.setText("Destino");

        labelItenerario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelItenerario.setForeground(new java.awt.Color(0, 0, 153));
        labelItenerario.setText("Itenerario");

        labelNroCompañia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNroCompañia.setForeground(new java.awt.Color(0, 0, 153));
        labelNroCompañia.setText("NroCompañia");

        labelDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(0, 0, 153));
        labelDNI.setText("DNI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNroBillete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(labelFecha)
                .addGap(60, 60, 60)
                .addComponent(labelHora)
                .addGap(52, 52, 52)
                .addComponent(labelOrigen)
                .addGap(65, 65, 65)
                .addComponent(labelDestino)
                .addGap(62, 62, 62)
                .addComponent(labelItenerario)
                .addGap(53, 53, 53)
                .addComponent(labelNroCompañia)
                .addGap(58, 58, 58)
                .addComponent(labelDNI)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNroBillete)
                    .addComponent(labelFecha)
                    .addComponent(labelHora)
                    .addComponent(labelOrigen)
                    .addComponent(labelDestino)
                    .addComponent(labelItenerario)
                    .addComponent(labelNroCompañia)
                    .addComponent(labelDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfac2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelItenerario;
    private javax.swing.JLabel labelNroBillete;
    private javax.swing.JLabel labelNroCompañia;
    private javax.swing.JLabel labelOrigen;
    // End of variables declaration//GEN-END:variables
}
